-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgtOkDvNcLcK4YHZYK
fmTGA+OkJoOWPztJcW6RNASsiGGgCgYIKoZIzj0DAQehRANCAARueCarmCcnoxDe
a2yIcvO6wyvRXHjZvUPmltvyo85a2vghgrCYYaI1q2swKWVI5KDLdVRw6YwEcN6W
eI5XHxbF
-----END PRIVATE KEY-----