version: 2.1
jobs:
  build-and-test:
    macos:
      xcode: 14.3.1
    steps:
      - checkout
      - run:
          name: Install CocoaPods
          command: |
            sudo gem install cocoapods
            pod install
      - run:
          name: Build and Test
          command: |
            xcodebuild clean test \
              -workspace CICDBlog.xcworkspace \
              -scheme "CICDBlog" \
              -destination "platform=iOS Simulator,name=iPhone 13 Pro"
workflows:
  build-and-test:
    jobs:
      - build-and-test