# fastlane/Fastfile
default_platform :ios

platform :ios do
  before_all do
    setup_circle_ci
  end

  desc "Runs all the tests"
  lane :test do
    # scan(
    #   include_simulator_logs: false
    # )
  swiftlint(
    mode: :lint,
    path: "./",
    output_file: "swiftlint.result.json",
    config_file: ".swiftlint.yml",
    raise_if_swiftlint_error: true,
    ignore_exit_status: true,
    executable: "${PODS_ROOT}/SwiftLint/swiftlint"
  )
  end

  desc "Ad-hoc build"
  lane :adhoc do
    match(type: "adhoc")
    gym(export_method: "ad-hoc")
  end
end