# fastlane/Fastfile
default_platform :ios

platform :ios do
  before_all do
    setup_circle_ci
  end

  desc "Runs all the tests"
  lane :test do
    # scan(
    #   include_simulator_logs: false
    # )
    swiftlint(
  mode: :lint,      # SwiftLint mode: :lint (default) or :autocorrect
  path: "/path/to/lint",       # Specify path to lint (optional)
  output_file: "swiftlint.result.json", # The path of the output file (optional)
  config_file: ".swiftlint.yml",     # The path of the configuration file (optional)
  raise_if_swiftlint_error: true,      # Allow fastlane to raise an error if swiftlint fails
  ignore_exit_status: true    # Allow fastlane to continue even if SwiftLint returns a non-zero exit status

)
  end

  desc "Ad-hoc build"
  lane :adhoc do
    match(type: "adhoc")
    gym(export_method: "ad-hoc")
  end
end